"""
Domain and payload models for LLM generation and RAG Question-Answering.
"""
from __future__ import annotations

from datetime import date
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from apps.auth.models import SecurityContext
from apps.retrieval.models import RetrievalFilters, RetrievalResult


class ChatMessage(BaseModel):
    """Represents a single message in a conversational or prompt exchange."""
    role: str = Field(..., description="Role of the speaker: 'system', 'user', or 'assistant'")
    content: str = Field(..., description="Message text content")


class LLMResponse(BaseModel):
    """Standardized response container from an LLM invocation."""
    content: str = Field(..., description="The main text generated by the model")
    thinking: Optional[str] = Field(None, description="Internal reasoning or thinking trace (e.g. from Qwen3)")
    model: str = Field(..., description="Model identifier used for generation")
    prompt_tokens: int = Field(0, description="Tokens evaluated from the prompt")
    completion_tokens: int = Field(0, description="Tokens generated in the completion")
    duration_seconds: float = Field(0.0, description="Total generation time in seconds")
    raw_response: Dict[str, Any] = Field(default_factory=dict, description="Raw provider response payload")


class Citation(BaseModel):
    """Citation linking an answer statement back to an authoritative retrieved chunk and source file."""
    chunk_id: str = Field(..., description="Unique chunk identifier, e.g. DOC-C-1000-ESTIMATE#c3")
    document_id: Optional[str] = Field(None, description="Parent document identifier")
    document_type: Optional[str] = Field(None, description="Document type, e.g. estimate, policy_contract")
    section: Optional[str] = Field(None, description="Section heading or structural anchor")
    page_number: Optional[int] = Field(None, description="Page number in original document (PDF/Word)")
    source_uri: Optional[str] = Field(None, description="Filesystem path or URI to the source file")
    file_link: Optional[str] = Field(None, description="Clickable file:// URI with optional page anchor")
    markdown_link: Optional[str] = Field(None, description="Formatted Markdown link for rich rendering")
    snippet: Optional[str] = Field(None, description="Text snippet from the referenced chunk")


class QARequest(BaseModel):
    """Request payload for the RAG Question-Answering flow."""
    query: str = Field(..., description="The user's question or search prompt", min_length=1)
    security_context: Optional[SecurityContext] = Field(
        None, description="Authenticated user security context enforcing RBAC/ABAC access control"
    )
    jwt_token: Optional[str] = Field(
        None, description="Optional raw JWT token to decode into SecurityContext if not already provided"
    )
    filters: Optional[RetrievalFilters] = Field(
        None, description="Optional caller-supplied retrieval filters (narrowing scope only)"
    )
    as_of_date: Optional[date] = Field(
        None, description="Point-in-time date for version-aware policy or loss retrieval"
    )
    top_k: int = Field(5, description="Number of context passages to supply to the LLM", ge=1, le=20)
    temperature: float = Field(0.0, description="Sampling temperature for generation (0.0 for deterministic answers)", ge=0.0, le=2.0)
    include_thinking: bool = Field(True, description="Whether to preserve the thinking trace in the response")


class QAResponse(BaseModel):
    """Comprehensive grounded response from the RAG Question-Answering flow."""
    query: str = Field(..., description="The original input question")
    answer: str = Field(..., description="The grounded, synthesized response from the model")
    citations: List[Citation] = Field(
        default_factory=list, description="Authoritative citations referencing retrieved source chunks"
    )
    retrieved_chunks: List[RetrievalResult] = Field(
        default_factory=list, description="Authorized and sanitized chunks passed to the LLM as context"
    )
    thinking: Optional[str] = Field(
        None, description="Extracted reasoning / thinking trace from Qwen3 if present and requested"
    )
    model: str = Field(..., description="Model identifier used for synthesis")
    latency_seconds: float = Field(0.0, description="Total end-to-end QA flow latency in seconds")
    usage: Dict[str, Any] = Field(
        default_factory=dict, description="Token usage and generation metrics"
    )
    security_user_id: Optional[str] = Field(
        None, description="Authenticated user ID whose security scope bounded the retrieval"
    )

    @property
    def answer_with_markdown_links(self) -> str:
        """
        Return the synthesized answer with raw [chunk_id] citation tags converted
        into clickable Markdown links pointing directly to the source files and pages.
        """
        formatted_answer = self.answer
        for citation in self.citations:
            if citation.file_link:
                # Replace [chunk_id] with [[chunk_id]](file_link)
                target = f"[{citation.chunk_id}]"
                replacement = f"[[{citation.chunk_id}]]({citation.file_link})"
                formatted_answer = formatted_answer.replace(target, replacement)
        return formatted_answer
